apiVersion: v1
kind: ConfigMap
metadata:
  name: master-data-api-env
  namespace: default
data:
  # Database
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_USER: "user"
  DATABASE_PASSWORD: "password"
  DATABASE_NAME: "telethai_master_data"
  
  # Redis
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
  
  # Node
  NODE_ENV: "development"
  PORT: "8001"
