apiVersion: v1
kind: Service
metadata:
  name: telethai-master-data-api
  namespace: default
  labels:
    app: telethai-master-data-api
spec:
  type: ClusterIP
  selector:
    app: telethai-master-data-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
