apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Chanwit21/telehealth-gitops
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
  - repoURL: https://github.com/Chanwit21/telehealth-gitops
    targetRevision: main
    path: .
    plugin:
      name: kustomize
      env:
      - name: KUSTOMIZE_ENABLE_ALPHA_COMMANDS
        value: "true"
