apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telehealth-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Chanwit21/telehealth-gitops
    targetRevision: main
    path: telehealth-helm
    helm:
      releaseName: telehealth
      values: |
        replicaCount: 2
        image:
          repository: ghcr.io/chanwit21/telethai-master-data-api
          tag: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
